[package]
name = "pn532"
version = "0.1.0"
authors = ["Martin Habovštiak <martin.habovstiak@gmail.com>"]

[features]
with_i2c = ["i2cdev"]

[dependencies]
i2cdev = { version = "0.3", optional = true }
